### ISSUE TITLE
Readme example not working

### ISSUE THREAD

**Issue by Slluxx** [SoheilMV/dnlib.BAML#1]
recordPropertyWithConverterRecord is not declared anywhere.

**Comment by Slluxx** [comment]
nvm i am just stupid. It should be a little more clarified though

**Comment by soheil-js** [comment]
The example written in README.md has a problem.

To solve the problem, refer to the following link and use its example:
https://github.com/SoheilMV/dnlib.BAML/blob/master/Test/Program.cs

Replace this code:
PropertyWithConverterRecord pwcr = record as PropertyWithConverterRecord;

**Comment by Slluxx** [comment]
Yeah, thanks.

Is there a way to delete a tag and their children? Or even work with tags, arguments etc as if it was a nested object? That would make things WAY simpler and allow for far greater possibilities
